DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits (
                                    hit_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL primary key,
                                    app VARCHAR(255) NOT NULL,
                                    uri VARCHAR(255) NOT NULL,
                                    ip VARCHAR(15) NOT NULL,
                                    timestamp TIMESTAMP WITHOUT TIME ZONE
);